In [1]:
# Purpose: Retrieve Telsa tweets using tweepy API
# Created on: June 01, 2018

# Twitter Connection
api_key = 'zw3115BQLJsWmbuvdatHz6VPx'
api_secret = 'gegWaJTpscJEA2ZJ30Fb4rPh7UchPcVt3xtNn8ErR1z69gflH6'
access_token = '77886913-cu9c0MIGtbeG051Qy83UtD34fiU9zgOkpgnNqMqrk'
access_secret = 'Zh1fMWF5K9Wtkhr8tKDsfCKzP5H9j60cnaRGoTpPLJeFD'

In [2]:
import tweepy #package we will use to interact with the API.
import pandas as pd

In [3]:
#Authorization

auth = tweepy.OAuthHandler(api_key, api_secret)
auth.set_access_token(access_token, access_secret)

api = tweepy.API(auth)

In [4]:
#Print to the console the tweets from your timeline
content_list = []
time_list = []
favorite_list = []
retweet_list = []
for i in range(0,165):
    public_tweets = api.user_timeline('elonmusk', page = i)
    for tweet in public_tweets:
        content_list.append(tweet.text)
        time_list.append(tweet.created_at)
        retweet_list.append(tweet.retweet_count)
        favorite_list.append(tweet.favorite_count)

In [5]:
time_list[len(time_list) - 1]

datetime.datetime(2015, 9, 2, 2, 24, 26)

In [6]:
import nltk
import gensim
from gensim.utils import tokenize
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import string
import re

stop_words = set(stopwords.words('english'))
# set of punctuation 
punctuation = set(string.punctuation)

# stemmer object
stemmer = PorterStemmer()

from nltk.tokenize import RegexpTokenizer


def clean(doc):
    # Remove stop words
    name_free = ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|rt","",doc.lower()).split())
    
    stop_free = ' '.join([term for term in name_free.split() if term not in stop_words])
    
    # Remove punctuation
    punc_free = ''.join(term for term in stop_free if term not in punctuation)
    
    stemmed = ' '.join(stemmer.stem(word) for word in punc_free.split())
    
    return stemmed

# clean every document in the corpus

clean_content_list = [clean(doc).split() for doc in content_list]

C:\Users\lk6me\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lk6me\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [7]:
from afinn import Afinn

# make an afinn object
afinn = Afinn()
afinn_list = []
# get sentiment for each document in the corpus 
# (unclean corpus because the clean one has some words the algorithm won't recognize)
for i in content_list:
    afinn_list.append(afinn.score(i))

In [8]:
all_words = []
for doc in clean_content_list:
    all_words += doc

word_frequencies = nltk.FreqDist(all_words)
word_frequencies.most_common(20)

[('tesla', 313),
 ('amp', 255),
 ('model', 218),
 ('car', 167),
 ('launch', 134),
 ('like', 131),
 ('ye', 128),
 ('good', 126),
 ('falcon', 126),
 ('3', 124),
 ('first', 105),
 ('next', 97),
 ('land', 95),
 ('go', 94),
 ('need', 90),
 ('one', 87),
 ('work', 87),
 ('rocket', 85),
 ('year', 83),
 ('get', 81)]

In [9]:
tesla = pd.DataFrame({'content':clean_content_list,'time':time_list, 'retweets':retweet_list,'favorites':favorite_list, 'afinn score':afinn_list})

In [10]:
tesla

,afinn score,content,favorites,retweets,time
0,0.0,"[uk, mid, 2019, rhd]",137,11,2018-06-01 08:29:40
1,8.0,"[sound, like, fun, adventur]",143,11,2018-06-01 08:25:09
2,2.0,"[uk, take, aero, ins, standard, wheel, amp, lo...",141,6,2018-06-01 08:23:54
3,9.0,"[model, 3, second, best, world, model, sx, sti...",1034,43,2018-06-01 02:47:53
4,2.0,"[filter, bacteria, virus, spore, pollen, amp, ...",13595,1413,2018-06-01 02:45:30
5,0.0,"[model, amp, x, also, acid, ga, filter, alkali...",3466,397,2018-06-01 02:41:22
6,0.0,"[open, door, social, media, user, come, behind...",0,1219,2018-06-01 02:14:23
7,4.0,"[cool, tesla, sx, hospit, oper, room, air, qua...",36759,5106,2018-06-01 02:13:19
8,0.0,[],35107,3669,2018-06-01 01:14:52
9,0.0,"[berlin, wurst, hat, meisten, curri]",1076,237,2018-05-31 20:24:45
10,0.0,"[ich, habe, der, universitt, ein, semest, deut...",2165,282,2018-05-31 20:18:58
11,0.0,[natrlich],1618,118,2018-05-31 19:39:57
12,0.0,[definit],1048,66,2018-05-31 19:37:32
13,3.0,"[best, analysi, model, 3, date, german]",9129,982,2018-05-31 19:29:57
14,0.0,"[finder, keeper]",45566,4016,2018-05-31 17:48:55
15,0.0,[pravduh],5121,449,2018-05-31 17:17:06
16,0.0,[hi],43010,2560,2018-05-31 14:41:20
17,0.0,"[lot, model, 3, deliveri, today, toronto, tomo...",0,860,2018-05-31 07:53:01
18,-1.0,"[gfischer, tri, adjust, tire, pressur, ask, te...",437,10,2018-05-31 05:18:53
19,-4.0,"[hell, week]",157596,26735,2018-05-31 04:18:00
20,0.0,"[uk, mid, 2019, rhd]",137,11,2018-06-01 08:29:40
21,8.0,"[sound, like, fun, adventur]",143,11,2018-06-01 08:25:09
22,2.0,"[uk, take, aero, ins, standard, wheel, amp, lo...",141,6,2018-06-01 08:23:54
23,9.0,"[model, 3, second, best, world, model, sx, sti...",1034,43,2018-06-01 02:47:53
24,2.0,"[filter, bacteria, virus, spore, pollen, amp, ...",13595,1413,2018-06-01 02:45:30
25,0.0,"[model, amp, x, also, acid, ga, filter, alkali...",3466,397,2018-06-01 02:41:22
26,0.0,"[open, door, social, media, user, come, behind...",0,1219,2018-06-01 02:14:23
27,4.0,"[cool, tesla, sx, hospit, oper, room, air, qua...",36759,5106,2018-06-01 02:13:19
28,0.0,[],35107,3669,2018-06-01 01:14:52
29,0.0,"[berlin, wurst, hat, meisten, curri]",1076,237,2018-05-31 20:24:45
...,...,...,...,...,...
3223,0.0,"[tesla, model, x, final, here, stuff, didnt, a...",0,566,2015-09-30 07:46:33
3224,4.0,"[tesla, model, x, suv, final, wonder, wed, hope]",0,1394,2015-09-30 07:44:30
3225,0.0,"[california, time]",719,178,2015-09-29 07:43:37
3226,0.0,"[model, x, launch, webcast, live, today, 8pm, ...",5097,3838,2015-09-29 07:39:41
3227,2.0,"[water, strong, evid, liquid, water, flow, pre...",0,42457,2015-09-28 16:12:34
3228,3.0,"[great, discuss, solarbatteri, empow, rural, c...",1973,1739,2015-09-27 01:02:35
3229,2.0,"[china, show, commit, climat, chang]",0,407,2015-09-26 05:38:34
3230,-2.0,"[week, static, fire, first, stage, upgrad, fal...",0,642,2015-09-25 08:53:39
3231,3.0,"[dinner, old, belgian, ironmongeri, best, menu...",1819,445,2015-09-25 00:44:09
3232,6.0,"[super, good]",296,39,2015-09-23 22:31:41
3233,0.0,"[midnight, dinner, berlin]",3409,855,2015-09-23 22:12:49
3234,0.0,"[casey, driven, 500, mile, tesla, model, 85d, ...",0,317,2015-09-16 16:44:58
3235,0.0,"[dragon, mar]",0,2440,2015-09-15 01:41:54
3236,1.0,"[expend, mode, falcon, heavi, send, fulli, loa...",3290,1640,2015-09-14 21:35:57
3237,5.0,"[dragon, 2, design, land, surfac, liquid, soli...",3300,1456,2015-09-14 21:26:37
3238,0.0,"[research, propos, use, falcondragon, mar, sam...",2071,1298,2015-09-14 21:24:22
3239,0.0,"[snowpack, sierra, nevada, hit, 500year, low, ...",0,2104,2015-09-14 16:13:49
3240,2.0,"[new, model, evolut, intellig, life, suggest, ...",2360,1283,2015-09-13 07:22:13
3241,2.0,[thank],861,136,2015-09-12 20:46:26
3242,0.0,"[btw, say, nuke, mar, layin, option]",7097,4185,2015-09-12 19:07:49
3243,0.0,"[crew, paner, unveil, interior, crew, dragon, ...",0,1416,2015-09-11 00:24:33
3244,0.0,"[first, look, interior, crew, dragon, nextgene...",0,1325,2015-09-11 00:24:27
3245,0.0,"[first, product, car, hand, sept, 29, fremont,...",1736,697,2015-09-02 20:59:53
3246,0.0,[definit],79,12,2015-09-02 20:57:45
3247,3.0,"[lithium, deal, exclus, amp, mani, conting, pr...",100,51,2015-09-02 20:39:18
3248,0.0,"[35k, price, unveil, march, preorder, sta]",3814,2566,2015-09-02 20:25:26
3249,0.0,"[model, 3, smaller, lower, cost, sedan, sta, p...",4899,4030,2015-09-02 20:22:20
3250,3.0,"[option, model, x, 5k, due, greater, size, amp...",1620,701,2015-09-02 20:17:47
3251,0.0,"[pad, 39a, futur, home, crew, launch, falcon, ...",0,1055,2015-09-02 06:30:41
3252,3.0,"[test, drive, new, tesla, dealer, dan, love]",0,1094,2015-09-02 02:24:26

In [ ]:
tesla.to_csv('tesla.csv', index=False)